services:
  - type: web
    name: pdf-to-docx-csv-xlsx-converter
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ghostscript
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
